#
# this is not currently in use, as we use docker
#
---
- name: Install node and docker repositories
  block:
    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
    - name: add nodejs repository
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_13.x focal main"
        state: "present"
    - name: Install the gpg key for Docker Repo
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu focal stable"
        state: "present"
